version: '3.9'
services:
  gclone-anime: &default
    image: anon0511/gclone-docker:latest
    restart: unless-stopped
    container_name: gclone-anime
    environment:
      - to_path=anime:/
      - from_path=/mnt/google/anime/
      - TZ=Europe/Berlin
      - intvl=60
      - minage=120
      - JOB=move
      - OPTS=--delete-empty-src-dirs --fast-list --drive-random-pick-sa --drive-rolling-sa --drive-rolling-count=1
    volumes:
      - /mnt/google/anime:/mnt/google/anime
      - /home/user/.config/rclone:/var/gclone/.config/rclone
      - /home/user/sarotate/all_accounts:/home/user/sarotate/all_accounts
      - /home/gclone:/gclone

  gclone-movies:
    <<: *default
    restart: unless-stopped
    container_name: gclone-movies
    environment:
      - to_path=movies:/
      - from_path=/mnt/google/movies/
      - TZ=Europe/Berlin
      - intvl=60
      - minage=120
      - JOB=move
      - OPTS=--delete-empty-src-dirs --fast-list --drive-random-pick-sa --drive-rolling-sa --drive-rolling-count=1
    volumes:
      - /mnt/google/movies:/mnt/google/movies
      - /home/user/.config/rclone:/var/gclone/.config/rclone
      - /home/user/sarotate/all_accounts:/home/user/sarotate/all_accounts
      - /home/gclone:/gclone

  gclone-tv:
    <<: *default
    restart: unless-stopped
    container_name: gclone-tv
    environment:
      - to_path=tv:/
      - from_path=/mnt/google/tv/
      - TZ=Europe/Berlin
      - intvl=60
      - minage=120
      - JOB=move
      - OPTS=--delete-empty-src-dirs --fast-list --drive-random-pick-sa --drive-rolling-sa --drive-rolling-count=1
    volumes:
      - /mnt/google/tv:/mnt/google/tv
      - /home/user/.config/rclone:/var/gclone/.config/rclone
      - /home/user/sarotate/all_accounts:/home/user/sarotate/all_accounts
      - /home/gclone:/gclone

